name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  terraform:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2

        - name: Set up Terraform
          uses: hashicorp/setup-terraform@v1

        - name: Configure AWS Credentials
          uses: aws-actions/configure-aws-credentials@v1
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: "us-east-1"

        - name: Terraform Init
          run: |
            cd infrastructure
            terraform init

        - name: Terraform Apply
          run: |
            cd infrastructure
            terraform apply -auto-approve

  build-and-deploy:
        needs: terraform
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2

        - name: Set up Node.js
          uses: actions/setup-node@v2
          with:
            node-version: '18'

        - name: Build Docusaurus Site
          run: |
            cd docusaurus
            npm install
            npm run build

        - name: Deploy to AWS
          run: |
            chmod +x $GITHUB_WORKSPACE/scripts/deploy.sh
            $GITHUB_WORKSPACE/scripts/deploy.sh
          env:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}